### ISSUE TITLE
compatibility with scala 2.11?

### ISSUE THREAD

**Issue by hhimanshu** [snopoke/google-safebrowsing2#5]
This breaks if we use it with scala 2.11.6

```
java.lang.NoClassDefFoundError: scala/ScalaObject
```

What needs to be done so that it is compatible with scala 2.11.6?

**Comment by snopoke** [comment]
I don't think this is a scala version issue. How did you install the Scala library? What is the output of scala -version?

**Comment by snopoke** [comment]
Actually I see you are correct. I think it just requires re-compilation of the `scala-http-client` library.

**Comment by snopoke** [comment]
I've submitted a PR with changes for 2.11 compatibility: https://github.com/snopoke/google-safebrowsing2/pull/6

**Comment by hhimanshu** [comment]
@snopoke 
where did you get `scala-http-client_2.11-1.0.jar`? I was trying to find it for many hours ;-)

Let me pull this new change and try to compile

**Comment by snopoke** [comment]
I made a new build from here: https://github.com/snopoke/scala-http-client.

I had to update the dependencies a bit: https://github.com/snopoke/scala-http-client/commit/d32006eb753a44464a32a63c9ed44138f2d60c45
